### ISSUE TITLE
Case insensitive filter?

### ISSUE THREAD

**Issue by wesley-murch** [robgridley/pace-api#10]
This could be an issue with Pace or something I've overlooked.
Is there any way to use `filter()` while being case insensitive? I ran into an issue looking up contacts by email address, in some cases they had uppercase letters in Pace and had to sidestep it using `contains()`.

    // Value in Pace is Wes@Domain.com

     // no result
    $pace->contact->filter('@email', 'wes@domain.com')->first();

     // returns correct object but isn't desirable
    $pace->contact->contains('@email', 'wes@domain.com')->first();
   
Is there an existing solution?

**Comment by robgridley** [comment]
I cannot find anything in the API documentation about case sensitivity, but can confirm your results. If you open a ticket with Pace Support, let me know what they say.

**Comment by robgridley** [comment]
I am closing this issue for now.

**Comment by wesley-murch** [comment]
I've been waiting on Pace support the whole time, will report back if and when they decide to be useful. Thanks.

**Comment by robgridley** [comment]
Yeah, that's pretty typical. You pay a crazy licensing fee to get access to the API, then they treat it's like some unsupported hack.

**Comment by wesley-murch** [comment]
I finally got a response from support. They said the only way to use a case insensitive filter if with "contains".
I mentioned this could be error prone and they said that's just the way it is.

**Comment by robgridley** [comment]
What about `startsWith()`? That might be slightly less error prone.

**Comment by wesley-murch** [comment]
Brilliant idea, I'll try it. Thanks!
