### ISSUE TITLE
dates

### ISSUE THREAD

**Issue by rkang30** [robgridley/pace-api#12]
Hi, 

I am trying to read and update the dates which are Carbon instances. 

For reading, 
I convert the Carbon instance to array when I read the date value. But I don't think this is the right way of doing it. Also, the PACE system only stores the date value but when I look at the carbon instance value in the API, the 'date' is displaying as date time value. 

e.g. +"date": "2015-07-31 04:00:00.000000"
      +"timezone_type": 3
      +"timezone": "UTC"  

For updating,
If I update the value with just a date ('Y-m-d'), would it cause an issue? Also, how do I update these date values?

Thanks,
Ryan

**Comment by rkang30** [comment]
I discovered the way for reading the carbon ($job->promiseDate->toDateString())  but I haven't found the way to update the carbon date...

**Comment by robgridley** [comment]
See the Carbon [documentation](http://carbon.nesbot.com/docs/). It extends PHP's built-in DateTime class.

Here are two examples which do the same thing:
```php
$job->promiseDate = new Carbon('2017-08-31');

$job->promiseDate = Carbon::createFromDate(2017, 8, 31);
```

**Comment by rkang30** [comment]
Awesome. Thank you!
