### ISSUE TITLE
fetching job parts from job product

### ISSUE THREAD

**Issue by rkang30** [robgridley/pace-api#13]
Hi, 

I am trying to fetch the total number of job parts under a job product when it's in json string format. 

Basically I am fetching the job products data via ajax. The php side (server side) that the ajax is requesting is below.

$jobProducts = $job->jobProducts()->sort('@id', true)->find() ;
return  $jobProducts; //this becomes json string

Generally, if I just had a $jobProduct model in php, I can fetch the number of job parts like below.

foreach($jobProducts as $jobProduct){
    $numofJobParts = count($jobProduct->jobParts());
}

But, I am currently turning the object to string in order to get a json string. This way, I can't fetch the number of job parts. 

What I am doing at the moment is that I basically looping the $jobProducts into 'foreach' and get the number number of job parts and append the each field value to a new array and return back to front side. 

This is inefficient. Because, I am looping it on the server side and client side in order to display the data.

Is there any better way of fetching the number of job parts?

Thanks,
Ryan

**Comment by robgridley** [comment]
```php
$jobProduct->jobParts()->get()->count();
```
I will not load any object/models. It will count the keys returned by the find.

**Comment by rkang30** [comment]
Cool. Thanks, @robgridley
