### ISSUE TITLE
How do I set the content of a file attachment?

### ISSUE THREAD

**Issue by wesley-murch** [robgridley/pace-api#14]
Do you happen to have any example code for writing attachments? Here's a sample of what I've been trying:

    $file = $this->pace->FileAttachment;
    $file->attachment = base64_encode(file_get_contents('example.pdf'));
    $file->baseObject = 'Quote';
    $file->baseObjectKey = 15310;
    $file->save();

This always produces the error "Uncaught Exception: SoapFault, attachment field is null".

Even if I read an existing attachment and try to update the "attachment" field it produces that error.

It seems that `attachment` is the primary key for `FileAttachment` as well as the vault key (not sure the difference). It's not used for the file content itself.

Any idea how is this actually done?

**Comment by robgridley** [comment]
Attachments are handled via a separate API service which I have not yet implemented. I have only implemented the create, read, update, delete, clone, find and version services.

**Comment by radoslavius** [comment]
For soap services I use this generator - https://github.com/wsdl2phpgenerator/wsdl2phpgenerator-cli

I create php script with this content
```
$generator->generate(
    new \Wsdl2PhpGenerator\Config(array(
        'inputFile' => 'http://<url of your pace server>/rpc/services/AttachmentService?wsdl',
        'outputDir' => 'Pace/Attachment',
        'namespaceName' => 'Pace\Attachment',
        'soapClientOptions' => array(
        	'authentication' => SOAP_AUTHENTICATION_BASIC,
        	'login' => '<username>',
        	'password' => '<password>',
        	'connection_timeout' => 60
        	)
    ))
);
```
and I run the script from the console. This generates the Pace directory with the generated classes. Then put the files into your project and use it.

For example:
```
public function addAttachment($file, $objectName, $objectKey, $category) {
    try {
        $content = base64_encode(file_get_contents($file));
        $mimeType = mime_content_type($file);
        $pathInfo = pathinfo($file);
        $attachment = new Attachment();
        $attachment->setName($pathInfo['basename'])->setContent($content)->setFileExtension('.' . $pathInfo['extension'])->setMimeType($mimeType);

        $attachmentService = new AttachmentService();
        $addAttachmentRequest = new addAttachment($objectName, $objectKey, '', $attachment);
        $response = $attachmentService->addAttachment($addAttachmentRequest);
        $attachmentKey = $response->getOut();

        $fileAttachment = $this->client->fileAttachment->read($attachmentKey);
        $fileAttachment->attachmentCategory = $category;
        $fileAttachment->save();
    } catch (\Exception $e) {
        return FALSE;
    }
    return TRUE;
}
```

Note: $this->client is client from robgridley/pace-api

**Comment by robgridley** [comment]
Thanks for that. I read through the API documentation and examples last night as well. I think there is room for improvement. I want the syntax to be something like:
```php
$job->attachFile($file);
```

**Comment by robgridley** [comment]
Initial support for attachments has been added to the master branch. A release is forthcoming. The syntax is as follows:

```php
$job->attach('example.txt', 'The Blue Jays are terrible this year');
// Adds an attachment to the job named "example.txt" with the very truthful content
// Returns a FileAttachment model so you can set the description, category, etc.

$job->attachments();
// Returns a KeyCollection of all FileAttachments attached to the job

$job->attachments()->first()->getContent();
// Returns the content of the first FileAttachment attached to the job
```

**Comment by robgridley** [comment]
Let me know what you think. I will probably publish a release on Monday, but I may have to bump to 1.0.x due to the way semantic versioning works. I am breaking some stuff with my latest commits.

**Comment by robgridley** [comment]
The attachments API has been finalized and v1.0.0 has been released. You can find the documentation [here](https://github.com/robgridley/pace-api#attachments).

**Comment by wesley-murch** [comment]
Is the only thing that makes this release PHP 7+ the use of null coalesce operator in the `Client/service` method, or is there something else?

**Comment by robgridley** [comment]
I think so. I no longer have access to PHP 5.x to test. My development environment and servers are all PHP 7.x.
