### ISSUE TITLE
adminStatus/@openJob VS @adminStatus

### ISSUE THREAD

**Issue by rkang30** [robgridley/pace-api#15]
Hi,

I am trying to understand between adminStatus/@openJob and @adminStatus.

1. $x = $job->filter('adminStatus/@openJob', true)->find();
2. $y = $job->filter('@adminStatus', '!=', 'C')->find();

Could you advise me the differences between them?

Thanks,
Ryan

**Comment by radoslavius** [comment]
This depends on your PACE system setup.
ad1) every JobStatus has bool attribute openJob, which means, that this filters out all jobs with the status with openjob sets to true
ad2) this is filter by one particular status with id "C"

**Comment by rkang30** [comment]
Thanks for your advice, @radoslavius

**Comment by robgridley** [comment]
What @radoslavius said.

```$job->filter('@adminStatus', '!=', 'C')->find();``` will return jobs which do not have a status of closed. It will still may return jobs with other statuses which are considered closed. X (cancelled) for example.

The opposite might be more clear. ```$job->filter('@adminStatus', 'O')->find();``` will return only jobs with a status of open. ```$job->filter('adminStatus/@openJob', true)->find();``` will return jobs with any status which is considered open. At our shop, that would include things like hold, waiting for proof, shipped, etc.

**Comment by rkang30** [comment]
Thank you for your thorough explanation. The jobs that I need to pull are not closed jobs. In other words, I would like to see all the jobs with various status (e.g. credit hold, waiting for proof, shipped...). I guess I can use "filter('adminStatus/@openJob', true)".
