### ISSUE TITLE
dates on update

### ISSUE THREAD

**Issue by rkang30** [robgridley/pace-api#16]
Hi,

I noticed that when I updated a date value, the date on efi system displayed one day earlier. 

For example, 
$inputs['to_kitting_date'] = '2017-09-01';
$job->U_ToKitting = new Carbon($inputs['to_kitting_date']);
$job->save();

The carbon date translated it as 2017-09-01 00:00:00 and the efi system calculated it as one day earlier than 2017-09-01 (which is 2017-08-31) as there's zero hour, min, and second. 

When I store it as below:
$job->U_ToKitting = new Carbon($inputs['to_kitting_date'].' 04:00:00');
$job->save();

The correct date was showing up on efi system.

Is there any better way of saving it other than what I have tried?

Thanks,
Ryan

**Comment by robgridley** [comment]
It looks like your PHP server and your Pace server are in different timezones. The Pace API sends dates as GMT date/times, but your Pace server records everything according to its timezone. My PHP client converts the date/time instances into the local timezone on the PHP sever.

From Pace (read):
Pace server timezone -> GMT -> PHP server timezone
To Pace (write):
PHP server timezone -> GMT -> Pace server timezone

**Comment by robgridley** [comment]
I forgot to mention that if you're not sure of the timezone on your PHP server, you can set it:

```php
date_default_timezone_set('America/Toronto');
```

**Comment by rkang30** [comment]
I just realized that I didn't set the timezone on my application. Thanks for your tips! I really appreciate it.
