### ISSUE TITLE
sorting job parts by job part number

### ISSUE THREAD

**Issue by rkang30** [robgridley/pace-api#18]
Hi,

I am having trouble sorting the job parts by job part number. Since the job part number is string, it doesn't sort the way I like. Is there any way that I can convert the type of job part number to integer in sorting?

if I run this code below:

    	$jobParts = $job->jobParts()
    	->sort('@jobPart', false)
    	->find();

The results are like below;

job part no: 01
job part no: 02
job part no: 03
job part no: 04
job part no: 05
job part no: 06
job part no: 07
job part no: 08
job part no: 09
job part no: 10
job part no: 100
job part no: 101
job part no: 102
job part no: 103
job part no: 104
job part no: 105
job part no: 106
job part no: 107
job part no: 108
job part no: 109
job part no: 11
job part no: 110

Thank you,
Ryan

**Comment by wesley-murch** [comment]
I know this doesn't address the underlying issue, but aren't the parts in the correct order when you don't use a sort at all?

**Comment by rkang30** [comment]
@wesley-murch 

No, I have tried it. It doesn't.

**Comment by rkang30** [comment]
Could anyone suggest any solutions please?? I am desperately needing this..

**Comment by rkang30** [comment]
never mind. It looks like it's somehow working even though it's broken in terms of queuing the parts... I am just going to use the sort('@jobPart', false) as is.
