### ISSUE TITLE
how to access report links

### ISSUE THREAD

**Issue by rkang30** [robgridley/pace-api#19]
Hi,

I see that the report links are being generated by javascript. Is it possible to fetch the direct links via API? (e.g. "Part Jackets" - under reports -> Production: Job Control).  

![image](https://user-images.githubusercontent.com/9328075/32505429-27567d0c-c3b0-11e7-9a4e-f831ce32901f.png)

Thanks,
Ryan

**Comment by robgridley** [comment]
I do not know of any way to get the report URLs. The closest thing I can offer you is querying the Report object to get a list of reports.

```php
$pace->model('Report')->filter('@baseObject', 'Job')->find();
```
