### ISSUE TITLE
how to access the history of jobPart

### ISSUE THREAD

**Issue by rkang30** [robgridley/pace-api#21]
Hi,

I am wanting to access the history of a job part but it seems like the api can't access the history. Could you help me how to get around this please? What I am trying to achieve is to get a date that the job part was created.

![image](https://user-images.githubusercontent.com/9328075/36429373-8802dffc-1620-11e8-848a-92979b2398ec.png)

**Comment by radoslavius** [comment]
Hi,
imho they are `dateSetup` and `timeSetUp` values on the `jobPart` object

![image](https://user-images.githubusercontent.com/3509024/36430042-7c6099a8-1654-11e8-908d-605b20622e79.png)
![image](https://user-images.githubusercontent.com/3509024/36430059-87650b72-1654-11e8-97fe-0a570b264f5a.png)
![image](https://user-images.githubusercontent.com/3509024/36430105-a0f20842-1654-11e8-97d6-8b1bdc8ca826.png)

**Comment by rkang30** [comment]
Thanks, @radoslavius
