### ISSUE TITLE
Do you anybody know anything about TransactionService?

### ISSUE THREAD

**Issue by radoslavius** [robgridley/pace-api#22]
How to use this service?
Thanks

**Comment by robgridley** [comment]
Is this a new service? I am still stuck on v27.

**Comment by Buda99999** [comment]
Hey, 
 Someone at Pace turned me on to this and I thought I'd add the TransactionService is a new one added in  v29. Sadly though within their API itself for php, they don't even have the classes or functions for the service built yet. The last actual update they added for php was back in 2014 and it wasn't with the main api just adding an example update. Sorry to distract.

**Comment by radoslavius** [comment]
I have examples only in java, but i don't know how use it in PHP. Here are resources which I received from the support - https://gist.github.com/radoslavius/d603d9889ec4fe34cb31d02a6d3ca6f1

**Comment by robgridley** [comment]
Can someone send me the SOAP WSDL for this service? That would allow me to get started.

**Comment by radoslavius** [comment]
[TransactionService.xml.zip](https://github.com/robgridley/pace-api/files/1935360/TransactionService.xml.zip)

**Comment by robgridley** [comment]
All done. See v1.1.0.

**Comment by robgridley** [comment]
See the new [readme](https://github.com/robgridley/pace-api#transactions) for v1.1.0.
