### ISSUE TITLE
Dates not automatically converted

### ISSUE THREAD

**Issue by bhartvigsen** [robgridley/pace-api#24]
The documentation has this to say about dates:  
  
"Dates are automatically converted to and from Carbon instances. "  
  
In my experience this is at least partially false. Example:
```
$job = $pace->model('Job');
$job->promiseDate = '2018-08-31';
...
$job->save();
```
All the date formats I tried, even the date format in the DateTimeMapping ('Y-m-d\TH:i:s.u\Z') fail to convert and you get a SoapFault on the toXml() method in DateTimeMapping.php.  
  
The workaround is to simply pass Carbon objects to the API wrapper when creating things. So my above snippet turns into:

```
$job = $pace->model('Job');
$job->promiseDate = new \Carbon\Carbon('2018-08-31');
...
$job->save();
``` 
  
This works perfectly. I don't necessarily think this is a bug, but the documentation is very misleading and because the wrapper doesn't trap this error scenario and output a reasonable error message I had to spend hours diving into the wrapper source code to uncover this mis-documented requirement.  
  
I would suggest that the documentation be updated to indicate that Carbon objects are needed when setting any date fields. Extra credit would be updating the toXml() method to throw a human-readable error if it's handed a non-Carbon datetime.

**Comment by robgridley** [comment]
2e5539c4f789db58294d34ab4f587e1517f4805d adds a type check. It will throw an exception if the $php argument passed to ``DateTimeMapping::toXml()`` is not a Carbon instance.
