### ISSUE TITLE
How to access most recent job history date

### ISSUE THREAD

**Issue by rkang30** [robgridley/pace-api#25]
Hi,

I would like to access Job/Product/Parts' history (url: .../object/Job/history/xxx) via API but don't know how to access it.

I used $job->history() but this returns only an empty history object. 

Thanks,

**Comment by rkang30** [comment]
Ok. Thanks for your advice. Is there any way that I could check the date and time of job/product/part's most recent update though?

**Comment by rkang30** [comment]
What I am trying to do is to check any jobs/products/parts on pace and update my local db if they are updated.

**Comment by robgridley** [comment]
There are a number of date and time fields on the Job Part which indicate recent activity. The editDate field is listed in the Object Model Browser, but it doesn't exist on my staging system when I read a random JobPart via the API.

**Comment by rkang30** [comment]
Do jobs and products have that value as well? I just quickly browse the job fields but don't see it..

**Comment by robgridley** [comment]
It doesn't look like it.

**Comment by rkang30** [comment]
Ok. Thank you.

**Comment by robgridley** [comment]
What kind of changes are you looking for? If the changes are occurring at the estimate level, you could use the version of the estimate associated with the job or job part to determine if things have changed.
