### ISSUE TITLE
ReportService API

### ISSUE THREAD

**Issue by lbakersd** [robgridley/pace-api#26]
Hello Rob,

I've been working with EFI's SDK for a few months and has been quite challenging. I found your pace-api noted in EFI's Forum and downloaded from github... I couldn't believe how easy it was to install and use within a day. I can't thank you enough.

I'm hoping you can help with this segment of the Report Service. I'm trying to execute a report and then download to a pdf.
http://IPADDRESS/reports/company:public/reportReader/view/NOTE+Jacket.pdf?init=pdf&prompt0=140780&key=10462&baseObjectKey=140780 

Having issues with curl etc... I was hoping you would, at some point, include ReportService to pace-api so reports could be easily executed via api call.  

Currently running Productivity Suite: v3.0 ePace (UI 3.0) - 27.12-833 (201601131253). I ran a current service list below to show that Report Services is available in 27 and a few others. I would know how to use the others even if they were available..
ReportService
InvokePaceConnect
GeoLocate
CustomizationService
InvokeProcess
InvokeAction
SystemInspector
FindCompany

Let me know you thoughts or if I can help is anyway. I'm very new to API and although I don't have the expertise to write the code, I'm able to figure out how to use the pace-api tool you have created.

Much appreciated,
Larry

**Comment by robgridley** [comment]
Hi, Larry.

Unfortunately, services tend to be implemented as I require them.

**Comment by robgridley** [comment]
I had some time over the holidays, so I implemented the [report service](https://github.com/robgridley/pace-api#reports). It's included in the 2.0 release.

**Comment by JoeKuhns** [comment]
Do you drink beer?  Or do you prefer other types of alcohol....
