### ISSUE TITLE
WAN connections fail sporadically

### ISSUE THREAD

**Issue by bhartvigsen** [robgridley/pace-api#27]
I encountered an issue with this API wrapper when I moved an app from development to production. Sending data to Pace over the Internet rather than over our LAN resulted in sporadic failures with this error:

SoapFault exception: [HTTP] Error Fetching http headers in /www/app/vendor/robgridley/pace-api/src/Services/CreateObject.php:20

I believe I've found a solution, editing Soap/Factory.php and adding the following to Factory::$options:

[
  'connection_timeout' => 5000,
  'cache_wsdl' => WSDL_CACHE_NONE,
  'keep_alive' => false,
  'compression' => SOAP_COMPRESSION_ACCEPT | SOAP_COMPRESSION_GZIP | 
  SOAP_COMPRESSION_DEFLATE
];

This seems to fix the issue (along with ini_set('default_socket_timeout', 5000)).

I'd rather not modify your library or fork it, but I know if I leave this hack in here it'll get nuked on a composer update 9 months from now and I'll have forgotten all about it.

What are your thoughts on properly integrating these settings into the library? I'm not sure if I stuck these options in the right place, there might be a better place, or perhaps add a parameter to the Pace class constructor so that end users can pass whatever params they want?

Thoughts?

**Comment by robgridley** [comment]
You can set those options in the SOAP factory.

```php
use Pace\Client as Pace;
use Pace\Soap\Factory as SoapFactory;

$soapFactory = new SoapFactory;
$soapFactory->setOption('connection_timeout', 5000);

$pace = new Pace($soapFactory, 'epace-staging.domain.com', 'apiuser', 'apipassword');
```
