### ISSUE TITLE
Click JobCost creates two records

### ISSUE THREAD

**Issue by rkang30** [robgridley/pace-api#29]
Hi,

When I create a job cost object for a click charge, I get two records. One with prodUnits  = 1 and another with empty prodUnits. The activity code (for clicks) that I supplied does have an inventory item. Is this happening because of the absence of inventory item?        

        $clicksJobCost = $pace->JobCost;
        $clicksJobCost->job = 'xxx'; 
        $clicksJobCost->jobPart = '04'; 
        $clicksJobCost->activityCode = '52598'; //click charge activity code
        $clicksJobCost->prodUnits = 1;
        $clicksJobCost->save();

Thanks,

**Comment by robgridley** [comment]
Resolved?

**Comment by rkang30** [comment]
No... I just closed it since it doesn't affect anything but just an empty record. It would be great if I know why though..

Thanks,

**Comment by rkang30** [comment]
By the way, do you happen to know how to delink job part material from job part press form? I need to remove the job part material but I get an error message saying '..still referenced by job part material press form.."

thanks,
