### ISSUE TITLE
PaceConnectResult XML file

### ISSUE THREAD

**Issue by rkang30** [robgridley/pace-api#31]
Hi,

I am trying to retrieve the xml file from the failed pace connect events. 

I can access the pace connect result object by the code below. But from here, I can't access and read the attached xml file.

$x = $pace->PaceConnectResult->read(xxxx);

Please help!

Thank you in advance.
Ryan

![image](https://user-images.githubusercontent.com/9328075/52574817-0f5f9e80-2deb-11e9-8587-f2451288c16b.png)

**Comment by robgridley** [comment]
The XML file is attached to the result.

```php
$result = $pace->model('PaceConnectResult')->read(99999);
$attachment = $result->fileAttachments()->first();
$attachment->getContent(); // the XML file content
```

**Comment by rkang30** [comment]
Hi robgridley,

I tried it with the code sample you provided me but didn't work. I have got the errors (please see below).

Unknown field 'paceConnectResult' on object 'FileAttachment'
