### ISSUE TITLE
File Attachment API

### ISSUE THREAD

**Issue by rkang30** [robgridley/pace-api#33]
Hi,

The efi told me that I will have to use file attachment api to connect to file attachment.

http://your host.com/rpc/services/AttachmentService?wsdl

Is this something I will have to make another connection in order to access the attachements? If so, do you have a php wrapper for this?

Thanks,
Ryan

**Comment by JoeKuhns** [comment]
In the read me it tells how to deal with attachments.  [https://github.com/robgridley/pace-api#attachments](url)

**Comment by rkang30** [comment]
Hi JoeKuhns,

I have tried it with what's on the readme but unsuccessful.  Please see below.

The errors (please see below).

$result = $pace->model('PaceConnectResult')->read(99999);
$attachment = $result->fileAttachments()->first();
$attachment->getContent(); // the XML file content

Unknown field 'paceConnectResult' on object 'FileAttachment'

**Comment by robgridley** [comment]
Which version of the library are you using? File attachment support was added in v1.0.0. If you are still running v0.1.x, then it won't work.

**Comment by rkang30** [comment]
Are you talking about your API version?

**Comment by robgridley** [comment]
Yes. v1.0.0 of this library added support for file attachments. I've tested it against v27 and v30 of Pace (I don't have access to any other versions).

**Comment by rkang30** [comment]
Yup! That works now!! Thanks for upgrading your API, robgridley.
