### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by JoeKuhns** [robgridley/pace-api#34]
Does anyone know the credentials for the pace SQL with write access?  someone here messed up an import and it would be a million times easier to fix it in the SQL directly.

**Comment by robgridley** [comment]
I only know the read-only credentials used for writing reports. You could write a PHP script to fix it with the API. :)

**Comment by JoeKuhns** [comment]
The field is locked for editing...

**Comment by robgridley** [comment]
Sometimes fields which are locked in the UI are accessible via the API, but you've probably already tested that.
