### ISSUE TITLE
filter error for currency comparison

### ISSUE THREAD

**Issue by rkang30** [robgridley/pace-api#36]
Hi,

I ran the code below and encountered the error below.

$jobMaterial = $pace->jobMaterial->contains('@unitPrice', '146.69')->first();

Error message:
Cannot compare string '146.69' to CurrencyAlt4

I put the string value('146.69') as the "unitPrice" is string. I don't know what 'CurrencyAlt4' is. 

It would be appreciated if you could shine some lights here.

Thanks,
Ryan

**Comment by JoeKuhns** [comment]
Try removing the quotes around 149.69.  I haven't played with currency much in the api.  But I have had success saving a cost and I sent it as a number not a string, so no quotes.
