### ISSUE TITLE
Assign existing contact to jobShipment

### ISSUE THREAD

**Issue by JoeKuhns** [robgridley/pace-api#37]
Simply, I am trying to assign a contact to a job shipment instead on  assigning the value to each field.

So, if I pull up a list of a customers contacts using...

`$contacts = $this->pace->Contact->filter('@customer', '=', $customer)->find();`

Then I take the id of one of those contacts and then create and  assign it to a jobShipment with the other required info like so....

`$newShipment = $this->pace->jobShipment;`
`$newShipment->job = $newJobNumber;`
`$newShipment->contactNumber = $contactid;`
`$newShipment->shipmentType = '8';`
`$newShipment->shipVia = $shiptype;`
`$newShipment->shipInNameOf = 2;`
`$newShipment->inventoryItem = $newItem->inventoryItem;`
`$newShipment->carton1Quantity = $totalquantity;`
`$newShipment->carton1Count = '1';`
`$newShipment->carton1Note = $descriptionstring;`
`$newShipment->save();`

I get nothing in the shipping details in pace.  Now if I manually take all of the information from the contact (name address, city, state, etc... and assign them to the appropriate fields, it works fine, except we now have a duplicate contact. Which would destroy the integrity of the contact list in the end.  So has anyone successfully assigned an existing contact to a shipment, I am at a loss on how to solve this one other than buy so support time, but it would be truly frustrating to buy the time and have them say can't do it too bad.  Thanks

**Comment by robgridley** [comment]
There is an intermediate object which you are missing. If you want to associate a Contact with a JobShipment, you first need to create a JobContact.

The following example assumes you already have Job and Contact objects loaded as `$job` and `$contact`.

```php
$jobContact = $pace->model('JobContact');
$jobContact->contact = $contact;
$jobContact->job = $job;
$jobContact->shipTo = true; // this is optional
$jobContact->save();

$jobShipment = $pace->model('JobShipment');
$jobShipment->job = $job;
$jobShipment->jobContact = $jobContact;
// ...
$jobShipment->save();
```

**Comment by JoeKuhns** [comment]
Once again, you save the day.  Thanks!
