### ISSUE TITLE
i can't connect to pace.

### ISSUE THREAD

**Issue by saung87** [robgridley/pace-api#39]
Hello, i am new to laravel and now i am using your api to communicate our pace server with the laravel and i got a SOAP communication error in the very beginning, after i have put the ip for the pace server and also the username and password, i try to connect with pace. But, the following error is keep showing up and i dont know how to solve it. Can you please check into it. The error is like this:

SOAP-ERROR: Parsing WSDL: Couldn't load from 'https://xxx.xxx.xxx.xxx/rpc/services/Version?wsdl' : failed to load external entity "https://xxx.xxx.xxx.xxx/rpc/services/Version?wsdl"

**Comment by radoslavius** [comment]
Hi,
and when you put this url in the browser, does it work for you?
If it working, try enabling ssl in soap client like this:
```
$soapFactory->setOption('stream_context', stream_context_create([
    'ssl' => [
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true,
    ]
]));
```
R

**Comment by JoeKuhns** [comment]
When you set this line what did you put in....

`new Pace(new SoapFactory(), 'pace.example.com', 'user', 'password', 'http');`

My guess is that instead of http at the end you have https.  I would try just changing the https to http first and go from there.

**Comment by saung87** [comment]
Hello @JoeKuhns ,

Thanks for your suggestion, now I can communicate with pace after I've made changes like you've pointed out. thanks for your time too @radoslavius .

**Comment by robgridley** [comment]
I'm closing this because @JoeKuhns and @radoslavius solved your problem.
