### ISSUE TITLE
Pace API v28.2 the request timed out 

### ISSUE THREAD

**Issue by Maybo2016** [robgridley/pace-api#4]
Hello,  I wrote a customized API that is currently writing large estimates to our Pace v27 production server.  Everything is working.

When I point a copy of the API at the Development server where V28.2 is installed, the API creates the estimate.  After that the API times out when it hits any kind of ObjectHttpBinding .

**Comment by Maybo2016** [comment]
Forgot to add the code that I was testing.

Estimate estimate = invokeActionHttpBinding.createEstimate(estimateInfo);Console.WriteLine( "Estimate " + estimate.estimateNumber  + " was successfully created for the customer HOUSE");
 estimate = invokeActionHttpBinding.calculateEstimate(estimate);
 Console.WriteLine("Estimate " + estimate.estimateNumber + " was successfully RECALCULATED created for the customer HOUSE");

**Comment by Maybo2016** [comment]
The Pace programmers were made aware of this issue and they fixed it.  There was a problem with an Apache Dll.

**Comment by robgridley** [comment]
I have an open ticket with Pace support to upgrade my staging server to version 28 so I can test issues like this one. We're still running version 27. Glad it worked out anyway.
