### ISSUE TITLE
re: manufacture qty is not saving

### ISSUE THREAD

**Issue by rkang30** [robgridley/pace-api#40]
Hi,

I am creating jobPart using the code below but the value of qtyToMfg is always set to 1 no matter what value I enter. In this case, I set it to 25 but it returns 1 after saving the jobPart.

                $jobPart = $pace->jobPart;
                $jobPart->job = "127629";
                $jobPart->jobProduct = 184012;
                $jobPart->jobPart = "74";
                $jobPart->description = "3 Panel Brochures - Eng & Fr - 74";
                $jobPart->flatSizeW = 8.55;
                $jobPart->flatSizeH = 10.54;
                $jobPart->pressSheetNumOut = 2;
                $jobPart->sheetsOffPress = 200;
                $jobPart->U_productionType = "ISM Print";
                $jobPart->printRunMethod = 5006;
                $jobPart->qtyToMfg = 25;
                $jobPart->save();

**Comment by robgridley** [comment]
I'm not sure exactly how qtyToMfg works. I always use item templates and qtyOrdered. However, have you tried updating the value of qtyToMfg after the create? Do your create and immediately update it. I have to do that for the quotedPrice field.

**Comment by JoeKuhns** [comment]
Rob is probably right but... I have had some luck setting some fields by setting it as a string, even though pace says it is an integer.  Try wrapping the 25 in quotes...
` $jobPart->qtyToMfg = "25";`

Also the object browser states "Enter the quantity to manufacture. If left blank, the system will default it to quantity ordered plus the allowable overs for the customer. "  So maybe quantity ordered needs to be set???

**Comment by rkang30** [comment]
Hi,

I tried to update the qtyToMfg after saving the jobPart and worked. But it's not good that I have to save twice...

**Comment by robgridley** [comment]
Did you try setting qtyOrdered like @JoeKuhns mentioned?

**Comment by rkang30** [comment]
I just don't want to mess up the data by setting the value of qtyOrdered as the same value of qtyToMfg. Are they the same values??

**Comment by JoeKuhns** [comment]
I never set qtyToMfg here for what we are using the api for, but when I look at a job in pace, it is setting it to be equal to quantityOrdered.

Did you try adding quotes around the "25". and see if it sets initially before the first save?

**Comment by rkang30** [comment]
Thank you @JoeKuhns ,

It worked!
