### ISSUE TITLE
JobNote - jobPart is not updating

### ISSUE THREAD

**Issue by rkang30** [robgridley/pace-api#41]
Hi,

I am trying to update 'jobPart' property of 'JobNote' object but doesn't seem to work. I have contacted EFI to see if it's their issue but haven't heard back from them yet. In the mean time, I would like to pick your brain as to how I need to save in order to update 'jobPart'.

Thanks,

        $jobNote = $pace->jobNote->read(550986);
        $jobNote->jobPart = '02';
        $jobNote->save();
        dd($jobNote);

**Comment by rkang30** [comment]
Hi,

I just heard back from EFI saying that they can update 'jobPart' via SOAP API. 

Can you advise me how to update the jobPart with your API wrapper??

Thanks,
Ryan

**Comment by JoeKuhns** [comment]
It looks like you are doing it correctly at a glance.

I typically run the read call like this…
`$jobNote = $pace->jobNote->filter('@id', '=', 550986)->first();`

But there isn't any reason yours shouldn't work.  Do you get any error, what does it do when you try to set it.  Also I hate to ask the obvious, but does the job Part 02 exist for that job?  If. that part doesn't already exist that would cause a fail.

**Comment by rkang30** [comment]
Hi @JoeKuhns ,

Thanks for your reply. Yes. the part that I am trying to move to exists. 

When I change from jobPart '01' to '02' using the code I mentioned earlier, it doesn't give me any error but the 'jobPart' value is still '01' when I print the object.

**Comment by rkang30** [comment]
Hi @JoeKuhns ,

Would you mind trying your test if you could change the jobPart value?

Thank you,

**Comment by JoeKuhns** [comment]
Got it on mine.  Here is what I did...

`				 $jobNote = $this->pace->jobNote->filter('@job', '=', 'Z1')->filter('@jobPart', '=', '01')->first();
				    $jobNote->jobPart = '02';
				    $jobNote->jobJobPart = 'Z1:01';
				    $jobNote->save();
				    print_r($jobNote);
`

I had to set jobJobPart to 'jobnumber:partnumber' and set the jobpart, If I didn't do them both it didn't hold.

**Comment by rkang30** [comment]
Wow. Ok. That's interesting. Thanks for trying it out. I appreciate it.

**Comment by rkang30** [comment]
I just tried it out as you advised and worked! 

Thank you, @JoeKuhns

**Comment by JoeKuhns** [comment]
Nice, Enjoy.

**Comment by rkang30** [comment]
@JoeKuhns ,

I had tried it with 'jobJobPart' only and worked as well. I guess I should only update 'jobJobPart' property...


        $jobNote = $pace->jobNote->read(521444);
        $jobNote->jobJobPart = "P38127:02";
        $jobNote->save();
        dd($jobNote);
