### ISSUE TITLE
Pagination is not working in my code

### ISSUE THREAD

**Issue by saung87** [robgridley/pace-api#43]
hello @robgridley ,

      When i try to do the paginate i got the following error
"Call to undefined method Pace\KeyCollection::links() (View: C:\laragon\www\productmanager\resources\views\parts\show.blade.php)"

in my controller i do the paginate and send the result to the view like this 
"$jobs = $pace->job
            ->filter('adminStatus/@openJob', true)
            ->find()->paginate(1,3);
return view('parts.show',compact('jobs'));"

and in my blade i try to show the list like this 
"@foreach($jobs as $jb)

                        <tr>
                            <td>{{$jb->enteredBy}}</td>
                            <td>{{$jb->job}}</td>
                            <td>{{$jb->customer}}</td>                          
                      </tr>

                    @endforeach

                </div>
                {{ $jobs->links() }}"

can you guys please help me pointing out what is wrong with this one again.. Thanks to you all..

**Comment by robgridley** [comment]
The key collection provides basic pagination (like a collection does in Laravel). To do what you're asking, you will need to implement Laravel's Paginator interface.

**Comment by saung87** [comment]
hello @robgridley  

thanks for the reply, but i'm new to laravel so i only know that i can do the paginate very simple in laravel like this:
$users = App\User::paginate(15);  <--- controller

in view:
<div class="container">
    @foreach ($users as $user)
        {{ $user->name }}
    @endforeach
</div>

{{ $users->links() }}

but, i am not sure how to manage with the pace api. Can you please point me out? thanks alot..

**Comment by robgridley** [comment]
When you call the paginate method on a Laravel model as part of a query, you get an instance of the LengthAwarePaginator class. It provides all of the magic (including the links method above).

When you call the paginate method on a Pace key collection (or Laravel collection) you only get the paginated items. No magic.

**Comment by saung87** [comment]
hello @robgridley 
So, if i have to call the paginate method on a model, which model i have to call in order to use with your pace api? Or, do i have to create my own model and controller to communicate with your pace api?

**Comment by saung87** [comment]
Hello @robgridley 

I got it now, the pagination is working now with the class that you've mentioned. i have to create the magic by myself. thanks :)
