### ISSUE TITLE
the package doesn't seem to work with php version 7.3.4 

### ISSUE THREAD

**Issue by rkang30** [robgridley/pace-api#44]
Hi,

I just upgraded my php version from 7.0 to 7.3.4 and ran a simple query (please see below).

$x = $pace->job->read(128910);

The job in Pace exists but it returned the error message (Class 'SoapClient' not found).

I removed the package and reinstalled it by composer. 

I printed the $pace object and compared it with the working one and there's no difference.

Thanks,
Ryan

**Comment by rkang30** [comment]
Sorry. I resolved this. Please ignore this.

I forgot to install php-soap package.. Iol

**Comment by robgridley** [comment]
I'm re-opening this for now because the Soap\Factory class should throw and exception with a useful error message.

**Comment by robgridley** [comment]
I have added ext-soap to the require section of composer.json in v1.1.0.
