### ISSUE TITLE
Is it possible to import part into existing estimate via API?

### ISSUE THREAD

**Issue by radoslavius** [robgridley/pace-api#47]
Hi,
can you help me with that?
Thanks Radek

![image](https://user-images.githubusercontent.com/3509024/62941407-387edd00-bdd6-11e9-855f-af04331b5ac3.png)

**Comment by robgridley** [comment]
I'm not sure exactly how you'd do that. Have you tried duplicating the part and changing the `@estimate` attribute?

```php
$estimatePartKey = 345678;
$newEstimateKey = 123456;

$part = $pace->model('EstimatePart')->read($estimatePartKey);
$part->estimate = $newEstimateKey;
$part->duplicate();
```

I haven't tested the above. It's just a guess.
