### ISSUE TITLE
Pass variable into grouped filer

### ISSUE THREAD

**Issue by JoeKuhns** [robgridley/pace-api#48]
I am using datatables.js with server side search, pagination, sort and filter.  While I have much of it working I cannot seem to pass a variable into the xpath grouped filter.  My code is below.

`->filter(function ($xpath) {
				        $xpath->contains('@job', $searched);
				        $xpath->orContains('@scheduledShipDate', $searched);
				        $xpath->orContains('@promiseDate', $searched);
				    })`

$searched is the variable I need to pass.  in a standard nested function I would do something like `->filter(function ($xpath) use $search {blah, blah, blah, `

But alas, it does not work.  Thanks for any help.

Joe

**Comment by radoslavius** [comment]
For faster responses, I recommend using queries to the database to read and thus sql.
Radek

**Comment by robgridley** [comment]
```php
$someModel->filter(function ($xpath) use ($searched) {
	$xpath->contains('@job', $searched)
		->orContains('@scheduledShipDate', $searched)
		->orContains('@promiseDate', $searched);
});
```

**Comment by JoeKuhns** [comment]
Thanks guys.  I screwed up earlier in the code, my bad.  Thanks.
