### ISSUE TITLE
FileAttachment Fun

### ISSUE THREAD

**Issue by JoeKuhns** [robgridley/pace-api#49]
As part of our on going development we are replacing many of the API calls with direct SQL select statements.  With that we are getting a massive improvement in speed and gaining some much desired flexibility.  But does anyone know how to get fileAttachments without the API, or a clever way through it?  Many thanks and happy new year!

Joe

**Comment by robgridley** [comment]
The contents of the attachments are not stored in the database, so I don't think you can bypass the API without direct access to the file system.

**Comment by JoeKuhns** [comment]
Thanks Rob, I played around a bit over the Holiday.  I can make the url's for the images in the "vault" as they call it, but you must be logged in to access the files in the vault, so that fails.  EFI says there is no way to access files in the vault with credentials, maybe I can curl them, it doesn't seem overly efficient, but I'll give it a shot thanks.
