### ISSUE TITLE
Shit.  32.01-3361 broke $image->getContent();

### ISSUE THREAD

**Issue by JoeKuhns** [robgridley/pace-api#56]
Upgraded this morning due to log4shell and now the following fails....

`$image = $this->pace->FileAttachment->filter('@baseObject', '=', 'InventoryItem')->filter('@baseObjectKey', '=', $id)->filter('@field', '=', 'thumbnail')->sort('@createdDate', true)->sort('@createdTime', true)->first();`
				
`$firstimage = $image->getContent();`
					
`echo base64_encode($firstimage);`

I get...   

<p>Type: SoapFault</p>
<p>Message: Service Unavailable</p>

when I print_r $firstimage.  I do get a successful response for $image.

Any help would be brilliant.  Thanks!

**Comment by JoeKuhns** [comment]
Figured it out maybe.....  Turns out we don't pay for full api access.  The update closed the loophole that allowed us to access the attachment service.

**Comment by robgridley** [comment]
You have to pay a separate license fee to access the attachment API? Jesus christ, EFI.
