### ISSUE TITLE
Updates PHP to 8.1.10 can't get objects

### ISSUE THREAD

**Issue by JoeKuhns** [robgridley/pace-api#57]
Running this code 

`$image = $this->pace->FileAttachment->filter('@baseObject', '=', 'InventoryItem')->filter('@baseObjectKey', '=', $id)->filter('@field', '=', 'thumbnail')->sort('@createdDate', true)->sort('@createdTime', true)->first();`

I get this error....

<p>Message: Key must not be null.</p>
<p>Filename: /vendor/robgridley/pace-api/src/Model.php</p>
<p>Line Number: 356</p>

Any thoughts?  I'll keep plugging away.  Thanks all.

**Comment by JoeKuhns** [comment]
Figured out its not in the getting attachment bit.  Its in the inventory item bit.  this also returns the same error.

`$this->pace->InventoryItem->filter('@id', '=', $id)->first();`

**Comment by robgridley** [comment]
Hi, Joe.

This is fixed in v2.0.4.
