### ISSUE TITLE
How do you do basic selects?

### ISSUE THREAD

**Issue by bhartvigsen** [robgridley/pace-api#6]
First, thanks for writing such a fantastically useful library. I've looked through the source code and I love how you used magic methods to do most of the heavy lifting, it's really elegant stuff. My question; your docs skip over how to do a basic 'select', how do you get everything without filtering? The docs jump right into filtering without showing how to do just grab everything. I've tried a number of attempts and haven't been successful--is there a technical restriction preventing this sort of thing or have I am I missing something really obvious? Thanks.

**Comment by robgridley** [comment]
As far as I can tell, there is no way to do a select without filtering. It seems to be a limitation of the Pace API, since if you omit the filter on a find call, you end up with a SOAP fault. If you can figure it out, I will gladly add the functionality.

**Comment by robgridley** [comment]
I tend to do stuff like this to get around the problem:

```php
$pace->model('CSR')->filter('@active', true)->get();
```

**Comment by radoslavius** [comment]
But not all objects have an active property. We usually do queries on data over the database, which is much faster. Especially for inquiries through more than one object.

**Comment by robgridley** [comment]
I hate the Pace database. Who ever named those columns should be flogged in the street. At least come up with a consistent naming scheme for relationship keys!

Another solution could be:
```php
$pace->model('CSR')->filter('@id', '!=', 0)->get();
```

That will return all CSRs, since it is impossible to have an ID which is equal to zero. You just have to be creative.

**Comment by bhartvigsen** [comment]
That's pretty crazy there is no way to do a basic select query through the API. Those workarounds will be suitable for my needs though, thanks a ton for the insights!
