### ISSUE TITLE
paginate

### ISSUE THREAD

**Issue by rkang30** [robgridley/pace-api#9]
Hi @robgridley 

Thank you for providing me the solution for the earlier questions. Now, I am trying to paginate the result like below but it seems to work.

		$jobs = $pace->job
		->filter('@adminStatus', 'O')
		->sort('customer/@custName')
		->paginate(1, 50)
		->filterKeys(function ($key){
			return strpos($key, 'P') !== 0;
		});

Could you advise on this please>

Thanks,
Ryan

**Comment by rkang30** [comment]
never mind. I resolved it.

		$jobs = $pace->job
		->filter('@adminStatus', 'O')
		->sort('customer/@custName')
		->find()
		->filterKeys(function ($key){
			return strpos($key, 'P') !== 0;
		})
		->paginate(1, 50);

**Comment by saung87** [comment]
@rkang30  Can you please share me how do you show the pagination link in the blade file? i am currently trying to do the pagination but i don't know how to show the pagination links in the blade file. Thank you.

**Comment by rkang30** [comment]
Hi saung87,

I call pagination by appending records upon the scrolling is at the bottom.  However, in your case, you might want to pass get parameters on each link. eg. mydomain.com/abc?page=1

Then, you can process it on your controller. 

In your controller,

You can call paginate after find(). 
..
->paginate($page, 50);

Good luck!

**Comment by saung87** [comment]
Hi @rkang30 ,

    Thanks for the reply. Here is my case i will share my controller and my view file and also i will show you the error message.

my controller is like this:
 $jobs = $pace->job
            ->filter('adminStatus/@openJob', true)
            ->find()->paginate(1,4);
       
        return view('parts.show',compact('jobs'));

in my view, i'm trying to show the list like this:

@foreach($jobs as $jb)

                        <tr>
                            <td>{{$jb->enteredBy}}</td>
                            <td>{{$jb->job}}</td>
                            <td>{{$jb->customer}}</td>
                        </tr>

                    @endforeach

                </div>
{{$jobs->links()}}

But, i got the following error:

ErrorException (E_ERROR)
Call to undefined method Pace\KeyCollection::links() (View: C:\laragon\www\productmanager\resources\views\parts\show.blade.php)

Thanks for your concern.

**Comment by saung87** [comment]
@rkang30  i got it now. thanks
